/** Etiquetas legibles por acción — claves `"modulo.accion"` (Sprint 20). */
export const ACTION_LABELS: Record<string, string> = {
  'usuarios.ver': 'Ver',
  'usuarios.crear': 'Crear',
  'usuarios.editar': 'Editar',
  'usuarios.eliminar': 'Eliminar',
  'usuarios.exportar': 'Exportar',
  'usuarios.reiniciar_contrasena': 'Reiniciar contraseña',
  'usuarios.bloquear': 'Bloquear',
  'usuarios.suspender': 'Suspender',
  'usuarios.reactivar': 'Reactivar',

  'materias.ver': 'Ver',
  'materias.crear': 'Crear',
  'materias.editar': 'Editar',
  'materias.eliminar': 'Eliminar',
  'materias.asignar': 'Asignar',
  'materias.cambiar_profesor': 'Cambiar profesor',
  'materias.cambiar_plan': 'Cambiar plan',

  'carreras.ver': 'Ver',
  'carreras.crear': 'Crear',
  'carreras.editar': 'Editar',
  'carreras.eliminar': 'Eliminar',
  'carreras.gestionar_plan': 'Gestionar plan',
  'carreras.gestionar_titulacion': 'Gestionar Producto de Titulación',

  'evaluaciones.ver': 'Ver',
  'evaluaciones.modificar': 'Modificar',
  'evaluaciones.aprobar_cambios': 'Aprobar cambios',
  'evaluaciones.rechazar_cambios': 'Rechazar cambios',
  'evaluaciones.publicar': 'Publicar',
  'evaluaciones.recalcular': 'Recalcular',

  'reportes.ver': 'Ver',
  'reportes.retroalimentar': 'Retroalimentar',
  'reportes.aprobar': 'Aprobar',
  'reportes.solicitar_correccion': 'Solicitar corrección',
  'reportes.eliminar': 'Eliminar',

  'leaderboard.consultar': 'Consultar',
  'leaderboard.modificar_puntos': 'Modificar puntos',
  'leaderboard.asignar_badges': 'Asignar badges',
  'leaderboard.recalcular_ranking': 'Recalcular ranking',

  'biblioteca.ver': 'Ver',
  'biblioteca.subir': 'Subir',
  'biblioteca.editar': 'Editar',
  'biblioteca.eliminar': 'Eliminar',
  'biblioteca.descargar': 'Descargar',
  'biblioteca.gestionar_categorias': 'Gestionar categorías',

  'foro.moderar': 'Moderar',
  'foro.eliminar_publicaciones': 'Eliminar publicaciones',
  'foro.eliminar_comentarios': 'Eliminar comentarios',
  'foro.suspender_usuarios': 'Suspender usuarios',
  'foro.resolver_reportes': 'Resolver reportes',
  'foro.destacar_publicaciones': 'Destacar publicaciones',

  'comunicacion.enviar_anuncios': 'Enviar anuncios',
  'comunicacion.crear_grupos': 'Crear grupos',
  'comunicacion.gestionar_conversaciones': 'Gestionar conversaciones',

  'configuracion.general': 'General',
  'configuracion.integraciones': 'Integraciones',
  'configuracion.api': 'API',
  'configuracion.zoom': 'Zoom',
  'configuracion.drive': 'Drive',
  'configuracion.correos': 'Correos',
  'configuracion.variables': 'Variables',

  'titulacion.ver': 'Ver',
  'titulacion.gestionar': 'Gestionar',
  'cursos.ver': 'Ver',
  'cursos.gestionar': 'Gestionar',
  'notificaciones.ver': 'Ver',
  'notificaciones.enviar': 'Enviar',
  'notificaciones.eliminar': 'Eliminar',
  'auditoria.consultar': 'Consultar',
  'seguridad.consultar': 'Consultar',
  'backups.gestionar': 'Gestionar',
  'incidencias.ver': 'Ver',
  'incidencias.gestionar': 'Gestionar',
  'matriculas.generar': 'Generar',
  'roles.ver': 'Ver',
  'roles.crear': 'Crear',
  'roles.editar': 'Editar',
  'roles.eliminar': 'Eliminar',
  'roles.asignar': 'Asignar',
  'administradores.ver': 'Ver',
  'administradores.crear': 'Crear',
  'administradores.editar': 'Editar',
  'administradores.suspender': 'Suspender',
  'administradores.eliminar': 'Eliminar',

  'finanzas.pagos': 'Pagos',
  'finanzas.becas': 'Becas',
  'finanzas.estados_cuenta': 'Estados de cuenta',
  'finanzas.facturacion': 'Facturación',
  'finanzas.descuentos': 'Descuentos',
  'finanzas.historial': 'Historial financiero',
}

export function actionLabel(permission: string): string {
  return ACTION_LABELS[permission] ?? permission
}
