import {
  Award,
  AlertTriangle,
  CheckCircle2,
  ClipboardList,
  CloudOff,
  Coins,
  FileCheck,
  FileText,
  Flag,
  Flame,
  GraduationCap,
  KeyRound,
  LogIn,
  Mail,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  MessageSquare,
  MessageSquareText,
  RefreshCw,
  Reply,
  ShieldOff,
  Sparkles,
  Star,
  Trophy,
  TrendingDown,
  TrendingUp,
  XCircle,
  Bell,
  type LucideIcon,
} from 'lucide-react'

/** Nombre de ícono (`NOTIFICATION_TYPE_ICON`) → componente de `lucide-react`. */
export const NOTIFICATION_ICON_COMPONENTS: Record<string, LucideIcon> = {
  ClipboardList,
  FileText,
  Award,
  GraduationCap,
  MessageCircle,
  MessagesSquare,
  FileCheck,
  CheckCircle2,
  XCircle,
  Reply,
  MessageSquare,
  Flag,
  MessageSquareText,
  Megaphone,
  AlertTriangle,
  ShieldOff,
  Mail,
  Coins,
  TrendingDown,
  Sparkles,
  TrendingUp,
  Trophy,
  Flame,
  Star,
  KeyRound,
  LogIn,
  RefreshCw,
  CloudOff,
}

export function resolveNotificationIcon(iconName: string): LucideIcon {
  return NOTIFICATION_ICON_COMPONENTS[iconName] ?? Bell
}
